//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicMediaPlayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int SongId { get; set; }
        public string SongTitle { get; set; }
        public Nullable<int> Times { get; set; }
        public string Artist { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> IsFavourite { get; set; }
        public int ListId { get; set; }
    
        public virtual PlayList PlayList { get; set; }
    }
}
